/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:22b356af-033d-46b1-830d-050a12b50495",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fIntQk14f",
    "aws_user_pools_web_client_id": "1obmofjrq8oa50pf1qqdkpgvf7",
    "oauth": {}
};


export default awsmobile;
